netbox_services/urls.py
from django.urls import path, include
from utilities.urls import get_model_urls
from .views import (
    ServiceRelatedDevicesView,
    ServiceRelatedInterfacesView,
    ServiceRelatedCablesView,
    ServiceRelatedVLANsView,
    ServiceRelatedPrefixesView,
    ServiceRelatedVRFsView,
    ServiceRelatedASNsView,
    ServiceRelatedRouteTargetsView,
    ServiceRelatedL2VPNsView,
    ServiceRelatedTunnelsView,
    ServiceRelatedVirtualMachinesView,
)

urlpatterns = [
    path('',
         include(get_model_urls('netbox_services', 'service', detail=False))
         ),
    path('<int:pk>/',
         include(get_model_urls('netbox_services', 'service', detail=True))
         ),
    path('<int:pk>/relate/devices/',
         ServiceRelatedDevicesView.as_view(),
         name='relate_devices',
         ),
    path('<int:pk>/relate/interfaces/',
         ServiceRelatedInterfacesView.as_view(),
         name='relate_interfaces',
         ),
    path('<int:pk>/relate/cables/',
         ServiceRelatedCablesView.as_view(),
         name='relate_cables',
         ),
    path('<int:pk>/relate/vlans/',
         ServiceRelatedVLANsView.as_view(),
         name='relate_vlans',
         ),
    path('<int:pk>/relate/prefixes/',
         ServiceRelatedPrefixesView.as_view(),
         name='relate_prefixes',
         ),
    path('<int:pk>/relate/vrfs/',
         ServiceRelatedVRFsView.as_view(),
         name='relate_vrfs',
         ),
    path('<int:pk>/relate/asns/',
         ServiceRelatedASNsView.as_view(),
         name='relate_asns',
         ),
    path('<int:pk>/relate/route_targets/',
         ServiceRelatedRouteTargetsView.as_view(),
         name='relate_route_targets',
         ),
    path('<int:pk>/relate/l2vpns/',
         ServiceRelatedL2VPNsView.as_view(),
         name='relate_l2vpns',
         ),
    path('<int:pk>/relate/tunnels/',
         ServiceRelatedTunnelsView.as_view(),
         name='relate_tunnels',
         ),
    path('<int:pk>/relate/virtual_machines/',
         ServiceRelatedVirtualMachinesView.as_view(),
         name='relate_virtual_machines',
         ),
]

netbox_services/models.py
from taggit.managers import TaggableManager

from django.db import models

from netbox.models import NetBoxModel

from tenancy.models import Tenant
from dcim.models import Device, Interface, Cable
from ipam.models import VRF, Prefix, VLAN, ASN, RouteTarget
from vpn.models import L2VPN, Tunnel
from virtualization.models import VirtualMachine
from circuits.choices import CircuitStatusChoices

from utilities.choices import ChoiceSet


class ServiceTypeChoices(ChoiceSet):
    CHOICES = [
        ('l2vpn', 'L2VPN'),
        ('l3vpn', 'L3VPN'),
        ('dia', 'DIA'),
        ('transit', 'IP Transit'),
        ('cdn', 'CDN'),
        ('voice', 'Voice')
    ]


class Service(NetBoxModel):
    type = models.CharField(
        choices=ServiceTypeChoices,
        verbose_name='Service Type',
        null=False,
        blank=False
    )
    service_id = models.CharField(
        verbose_name='Service ID',
        unique=True,
        null=False,
        blank=False
    )
    status = models.CharField(
        choices=CircuitStatusChoices,
        verbose_name='Status',
        null=True,
        blank=True
    )
    tenant = models.ForeignKey(
        Tenant,
        on_delete=models.PROTECT,
        verbose_name='Service Tenant',
        null=True,
        blank=True
    )
    devices = models.ManyToManyField(
        Device,
        verbose_name='Related Devices',
    )
    interfaces = models.ManyToManyField(
        Interface,
        verbose_name='Related interfaces',
    )
    cables = models.ManyToManyField(
        Cable,
        verbose_name='Related Cables/XConnects',
    )
    vlans = models.ManyToManyField(
        VLAN,
        verbose_name='Related VLANs',
    )
    prefixes = models.ManyToManyField(
        Prefix,
        verbose_name='Related IP Prefixes',
    )
    vrfs = models.ManyToManyField(
        VRF,
        verbose_name='Related VRF',
        blank=True
    )
    asns = models.ManyToManyField(
        ASN,
        verbose_name='Related Autonomous Systems',
    )
    route_targets = models.ManyToManyField(
        RouteTarget,
        verbose_name='Related Route Targets',
    )
    l2vpns = models.ManyToManyField(
        L2VPN,
        verbose_name='Related Route Targets',
    )
    tunnels = models.ManyToManyField(
        Tunnel,
        verbose_name='Related Tunnels',
    )
    virtual_machines = models.ManyToManyField(
        VirtualMachine,
        verbose_name='Related Virtual Machines',
    )
    tags = TaggableManager(
        related_name='netbox_services_service_set',
    )

    class Meta:
        verbose_name = 'Service'
        verbose_name_plural = 'Services'
        ordering = ['service_id']

    def __str__(self):
        return f"{self.service_id}"

    def get_absolute_url(self):
        return f"/plugins/services/{self.pk}/"

    def get_status_color(self):
        return CircuitStatusChoices.colors.get(self.status)

netbox_services/templates/netbox_services/service.html
{% extends 'generic/object.html' %}
{% load i18n %}
{% load helpers %}
{% load buttons %}

{% block content %}
<div class="row">
  <div class="col col-6 col-xl-6">
    <div class="card">
      <h2 class="card-header">{% trans "General" %}</h2>
      <table class="table table-hover attr-table">
        <tr>
          <td style="width: 20%">{% trans "Service ID" %}</td>
          <td>{{ object | linkify }}</td>
        </tr>
        <tr>
          <td style="width: 20%">{% trans "Type" %}</td>
          <td>{{ object.get_type_display }}</td>
        </tr>
        <tr>
          <td style="width: 20%">{% trans "Tenant" %}</td>
          <td>{{ object.tenant | linkify }}</td>
        </tr>
        <tr>
          <td style="width: 20%">{% trans "Status" %}</td>
          <td>{% badge object.get_status_display bg_color=object.get_status_color %}</td>
        </tr>
        <tr>
          <td style="width: 20%">{% trans "Tags" %}</td>
          <td>{% for tag in object.tags.all %}{{ tag  | linkify }}</br>{% if not forloop.last %}, {% endif %}{% empty %}None{% endfor %}</td>
        </tr>
      </table>
    </div>
  </div>
</div>
<div class="row">
  <div class="col col-6 col-xl-6">
    <div class="card">
      <h2 class="card-header">{% trans "Devices & Interfaces" %}</h2>
      <table class="table table-hover attr-table">
        {% for device in object.devices.all %}
        <tr>
          <td style="width: 20%">{% if forloop.first %}{% trans "Device" %}{% endif %}</td>
          <td style="width: 40%">{{ device|linkify }}</td>
          <td style="width: 40%">
            {% with related_ifaces=object.interfaces.all|dictsort:"name" %}
              {% for iface in related_ifaces %}
                {% if iface.device == device %}
                  {{ iface|linkify }}{% if not forloop.last %}<br> {% endif %}
                {% endif %}
              {% empty %}None{% endfor %}
            {% endwith %}
          </td>
        </tr>
        {% empty %}
        <tr>
          <td style="width: 20%">{% trans "Device" %}</td>
          <td colspan="2">None</td>
        </tr>
        {% endfor %}
        <tr>
          <td style="width: 20%"></td>
          <td style="width: 40%"><a href="{% url 'plugins:netbox_services:relate_devices' pk=object.pk %}">Assign devices</a></td>
          <td style="width: 40%"><a href="{% url 'plugins:netbox_services:relate_interfaces' pk=object.pk %}">Assign interfaces</a></td>
        </tr>
        <tr>
          <td style="width: 20%">{% trans "Cables" %}</td>
          <td style="width: 40%">{% for cable in object.cables.all %}{{ cable|linkify }}<br>{% if not forloop.last %}, {% endif %}{% empty %}None{% endfor %}</td>
          <td><a href="{% url 'plugins:netbox_services:relate_cables' pk=object.pk %}">Assign</a></td>
        </tr>
      </table>
    </div>
  </div>
</div>
<div class="row mt-3">
  <div class="col col-6 col-xl-6">
    <div class="card">
      <h2 class="card-header">{% trans "Network" %}</h2>
      <table class="table table-hover attr-table">
        <tr>
          <td style="width: 20%">{% trans "VLANs" %}</td>
          <td>{% for vlan in object.vlans.all %}{{ vlan  | linkify }}</br>{% if not forloop.last %}, {% endif %}{% empty %}None{% endfor %}</td>
          <td><a href="{% url "plugins:netbox_services:relate_vlans" pk=object.pk %}">Assign</td>
        </tr>
        <tr>
          <td style="width: 20%">{% trans "Prefixes" %}</td>
          <td style="width: 40%">{% for prefix in object.prefixes.all %}{{ prefix  | linkify }}</br>{% if not forloop.last %}, {% endif %}{% empty %}None{% endfor %}</td>
          <td style="width: 40%"><a href="{% url "plugins:netbox_services:relate_prefixes" pk=object.pk %}">Assign</td>
        </tr>
        <tr>
          <td style="width: 20%">{% trans "ASNs" %}</td>
          <td>{% for asn in object.asns.all %}{{ asn  | linkify }}</br>{% if not forloop.last %}, {% endif %}{% empty %}None{% endfor %}</td>
          <td style="width: 40%"><a href="{% url "plugins:netbox_services:relate_asns" pk=object.pk %}">Assign</td>
        </tr>
      </table>
    </div>
  </div>
</div>
<div class="row mt-3">
  <div class="col col-6 col-xl-6">
    <div class="card">
      <h2 class="card-header">{% trans "VPNs" %}</h2>
      <table class="table table-hover attr-table">
        <tr>
          <td style="width: 20%">{% trans "VRFs" %}</td>
          <td style="width: 40%">{% for vrf in object.vrfs.all %}{{ vrf  | linkify }}</br>{% if not forloop.last %}, {% endif %}{% empty %}None{% endfor %}</td>
          <td style="width: 40%"><a href="{% url "plugins:netbox_services:relate_vrfs" pk=object.pk %}">Assign</td>
        </tr>
        <tr>
          <td style="width: 20%">{% trans "RTs" %}</td>
          <td style="width: 40%">{% for rt in object.route_targets.all %}{{ rt  | linkify }}</br>{% if not forloop.last %}, {% endif %}{% empty %}None{% endfor %}</td>
          <td style="width: 40%"><a href="{% url "plugins:netbox_services:relate_route_targets" pk=object.pk %}">Assign</td>
        </tr>
        <tr>
          <td style="width: 20%">{% trans "L2VPNs" %}</td>
          <td style="width: 40%">{% for l2vpn in object.l2vpns.all %}{{ l2vpn  | linkify }}</br>{% if not forloop.last %}, {% endif %}{% empty %}None{% endfor %}</td>
          <td style="width: 40%"><a href="{% url "plugins:netbox_services:relate_l2vpns" pk=object.pk %}">Assign</td>
        </tr>
        <tr>
          <td style="width: 20%">{% trans "Tunnels" %}</td>
          <td style="width: 40%">{% for tunnel in object.tunnels.all %}{{ tunnel  | linkify }}</br>{% if not forloop.last %}, {% endif %}{% empty %}None{% endfor %}</td>
          <td style="width: 40%"><a href="{% url "plugins:netbox_services:relate_tunnels" pk=object.pk %}">Assign</td>
        </tr>
      </table>
    </div>
  </div>
</div>
<div class="row mt-3">
  <div class="col col-6 col-xl-6">
    <div class="card">
      <h2 class="card-header">{% trans "Virtualization" %}</h2>
      <table class="table table-hover attr-table">
        <tr>
          <td style="width: 20%">{% trans "VMs" %}</td>
          <td>{% for vm in object.virtual_machines.all %}{{ vm  | linkify }}</br>{% if not forloop.last %}, {% endif %}{% empty %}None{% endfor %}</td>
          <td style="width: 40%"><a href="{% url "plugins:netbox_services:relate_virtual_machines" pk=object.pk %}">Assign</td>
        </tr>
      </table>
    </div>
  </div>
</div>
{% endblock %}